__author__ = 'Wang Jingran'
__version__ = '1.0'
__date__ = '2024.2.24'
__license__ = 'MIT License'
__copyright__ = 'Copyright'
__status__ = 'Development'
__email__ = 'jrwangspencer@stu.suda.edu.cn'
__github__ = 'https://github.com/Spencer-JRWang/APMA'
__description__ = 'Auto Protein Mutation Analyzer'
__keywords__ = 'Protein Mutation, Mutation Analysis, Machine Learning'
__site__ = "FoldX, Prody, DSSP, NACEN, Rate4site, BLAST, Clusteral Omega"
__department__ = "Department of Bioinformatics, Soochow University Medical College"
